### ISSUE TITLE
Request for elaboration on 3dome_data_generator parameters

### ISSUE THREAD

**Issue by monajalal** [PyramidHe/PVNet#8]
Hi, Could you please show an example of how the passed parameters are for the following command?

```

python 3dome_data_generator/create_synth_dataset --conf path/to/camera/conf --mesh path/to/mesh --images path/to/images
--bkgs path/to/bkgs/images --out path/to/output/folder

```

For example, could you shod how your camera conf file looks like? also why do you need both images and background images? It is rather unclear. Further, for backgrounds, do you use this folder?

```
(base) mona@ada:/data2/data/SUN2012pascalformat$ ls
total 1.8M
drwxr-xr-x 3 mona mona 4.0K Oct 30  2012 ImageSets
drwxr-xr-x 5 mona mona 4.0K Oct 30  2012 .
-rw-r--r-- 1 mona mona 207K Oct 30  2012 report.txt
drwxr-xr-x 2 mona mona 764K Oct 30  2012 JPEGImages
drwxr-xr-x 2 mona mona 772K Oct 30  2012 Annotations
drwxrwxr-x 7 mona mona 4.0K Nov 28 10:27 ..

```

I am interested in using 3dome_data_generator to create synthetic dataset for PVNet.

Also, would it please be possible to share an example of a (dummy) dataset you have created using this script?

**Comment by PyramidHe** [comment]
Hi Mona,
that script was used to convert a custom dataset, which I don't own, to the format used by PVNet. By the way you can ignore it if you are interested in using your own data and follow the instructions provided by the original implementation.
